version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: Navidrome
    user: 1000:1000 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    volumes:
      - "/mnt/Arch/@home/edu/Music/.data:/data"
      - "/mnt/Arch/@home/edu/Music:/music:ro"
